name: Push image to GCR
on:
  push:
    branches: [ main ]
jobs:
  pull-push-gcr:
    name: Pull image and push it to GCR (to test for errors)
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: demo-crp
      PROJECT_ID: gilad-dev-k8s
    steps:
      - name: Checkout
      uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: $ {{ env.PROJECT_ID }}
          export_default_credentials: true
      - name: Pull docker image 
        run: docker pull pwstaging/demo-crm:latest 

      - name: Configure Docker client
        run: |-
          gcloud auth configure-docker --quiet

      - name: Push Docker image to GCR
        env: 
          GIT_TAG: v0.1.0
        run: |-
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
